FROM ruby:2.3.1

RUN apt-get update --fix-missing
RUN apt-get install -y wkhtmltopdf

ENV DOCKER true

WORKDIR /app

ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install --with=server

ADD . /app
